### PR TITLE
Update utopia_ascension_l_english.yml

### PR DESCRIPTION
**Pull request by BurningRainbow**
a brief gateway into the Shroud.\n\nNow that we have established an initial psionic link, we will be able to access the Shroud through the §HContacts§! menu in the future. To make any kind of meaningful forays into this realm and meet the beings who dwell there, we will likely have to make use of special psionic emitters to extend our psychic reach. This will consume a tremendous amount of energy

翻译不好

### CODE REVIEW

**Comment by BurningRainbow** [comment]
The Séance
Conclave of Telepaths

这俩个词，感觉翻译有难度

我翻译成了降神会和灵能教主团

**Comment by Tianchenglipu** [comment]
很好，完美撞车 =。=

**Comment by BurningRainbow** [comment]
没事，也就几行而已。而且我觉得关于灵能大漩涡那一句你那边翻译的更恰当。

**Comment by Tianchenglipu** [comment]
灵能的描述看得我好想做个变革者的AP，全员觉醒为不会自然死亡的变革者，并获得特殊部件GN Sol Reactor，佩带此部件的舰船进入任何帝国的领土会立即建立联系，而且全帝国对我国好感度+100 →_→

**Comment by BurningRainbow** [comment]
天人邪教！食我人革联铁拳！

**Comment by BurningRainbow** [comment]
怎么删除这个？

**Pull request closed without merging**
